/* Frost Lingo — the single source of truth for The Permafrost and for Simone.
 *
 * Transcribed from Frost Lingo 101 (Frost_Lingo_v1.pdf).
 *
 * Slug rule: lowercase, non-alphanumerics collapsed to single hyphens, no
 * leading or trailing hyphen. Slugs are permanent — they become URLs that
 * Simone links to and that people paste into chat. Add entries freely;
 * never rename a slug.
 *
 * Fields
 *   slug      permanent id, used in /#/term/<slug>
 *   term      as written and capitalised in the studio
 *   aka       abbreviations, plurals, alternate spellings, likely misspellings
 *   short     the one-line definition
 *   long      why and when it applies
 *   example   the term used in a sentence, the way someone here would say it
 *   saidBy    who is speaking in that example, and their role
 *   related   slugs of neighbouring entries
 *   category  section from the source deck
 *   audience  who the term is for: "all", "designers", "devs", "content"
 */

export const CATEGORIES = [
  "Process Related",
  "Design Process",
  "Design Terms",
  "Design Artifacts",
  "Miscellaneous",
];

export const VOCABULARY = [
  /* ---------------------------------------------------------------
     PROCESS RELATED
     --------------------------------------------------------------- */
  {
    slug: "base-deliverables",
    term: "Base Deliverables",
    aka: ["base deliverable", "base scope"],
    short: "The core tasks agreed upon, excluding client revisions, to be completed within a specific timeframe.",
    long: "Base deliverables and their timeline must be identified so the team knows what to work on. This is done as early as possible by the Project Manager or Coordinator together with the client.",
    example: "Our base deliverable for this sprint consists of high-fidelity screens for the dashboard and login screens.",
    saidBy: "Mayeth, Project Manager",
    related: ["change-logs", "rework", "cards"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "buffer-lane",
    term: "Buffer Lane",
    aka: ["buffer", "buffer lanes"],
    short: "A waiting area in Trello. Cards sit there until someone is ready to work on them — once a card is finished in one stage it moves to the buffer lane, ready for the next step.",
    long: "This is built into our Trello so that cards needing to move between columns don't have to wait in place. It keeps a balance between work items and lets designers manage their tasks effectively.",
    example: "Moving this card to the buffer lane while waiting for the next steps for this.",
    saidBy: "Miles, Design Ops",
    related: ["cards", "pipeline", "working-on-lane", "man-the-lane"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "bugs-and-issues",
    term: "Bugs and Issues",
    aka: ["bugs", "bug", "issues", "issue"],
    short: "Errors or design flaws in screens found during development. These are addressed during the DQA process.",
    long: "Bugs and issues should be identified during DQA. Catching them matters because we hand over pixel-perfect designs to our clients.",
    example: "Addressed the bugs on this page. Will close the card for this.",
    saidBy: "Enzo, Frontend Developer",
    related: ["dqa", "validate-issues", "passed-qa-validation"],
    category: "Process Related",
    audience: ["designers", "devs"],
  },
  {
    slug: "cards",
    term: "Cards",
    aka: ["card", "trello card", "trello cards"],
    short: "Trello cards representing project tasks, placed in the appropriate lanes on Trello boards. Cards move across the board from left to right.",
    long: "Cards must be filed on Trello for any work to be done, as this is part of one's scorecard. On our Figma files, filing cards is automated through Hermes.",
    example: "Added all cards we'll be working on to our Trello board.",
    saidBy: "Miro, Project Coordinator",
    related: ["buffer-lane", "pipeline", "production-backlogs", "change-logs"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "change-logs",
    term: "Change Logs",
    aka: ["change log", "changelog", "changelogs", "additional request"],
    short: "Revisions or modifications requested by clients or within the team for previously delivered work. Usually tagged as \"Additional Request\" on cards.",
    long: "These are identified separately from base deliverables and get their own card. You can file a change card automatically through the Figma comment keyword \"@change\".",
    example: "Added some change logs cards to our backlog; please address per our client's request.",
    saidBy: "Miro, Project Coordinator",
    related: ["base-deliverables", "rework", "cards"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "chronicles",
    term: "Chronicles",
    aka: ["chron", "chrons", "daily chron"],
    short: "A written journal prepared by the team highlighting their achievements, usually posted on Mondays, Wednesdays, and Fridays.",
    long: "Chron is a supplement for the production team to practice their craft. It also acts as an update on our progress for clients, presented similar to a portfolio.",
    example: "Chron for today is posted! It's for client viewing already.",
    saidBy: "Karen, Content Writer",
    related: ["daily-checkpoint", "daily-standup"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "daily-checkpoint",
    term: "Daily Checkpoint",
    aka: ["cp", "checkpoint", "checkpoints"],
    short: "An end-of-day meeting for the team to align on daily accomplishments, progress, and project or task statuses.",
    long: "During checkpoint, members of the production team share their accomplishments for the day, either verbally or via screen share. Usually held at 5PM.",
    example: "Please give your updates later during our checkpoint.",
    saidBy: "Miro, Project Coordinator",
    related: ["daily-standup", "chronicles", "ho"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "daily-standup",
    term: "Daily Standup",
    aka: ["dsu", "standup", "stand up"],
    short: "A brief morning meeting where the team discusses objectives, tasks, blockers, and clarifications for the day.",
    long: "DSU meetings should be quick. You must come prepared with your objectives and blockers.",
    example: "I have blockers I need to raise during our DSU.",
    saidBy: "Don, Team Lead",
    related: ["daily-checkpoint", "chronicles"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "dqa",
    term: "DQA",
    aka: ["design qa", "design quality assurance", "d qa"],
    short: "Design Quality Assurance — a process where designers review developer output to make sure it matches the design, checking quality and identifying bugs.",
    long: "DQA is crucial to ensure the developed version is error-free and follows the design accurately. It's the last step from the team before releasing output to clients.",
    example: "This page is now for DQA, thank you!",
    saidBy: "Anna, Technical Lead for Development",
    related: ["bugs-and-issues", "validate-issues", "passed-qa-validation"],
    category: "Process Related",
    audience: ["designers", "devs"],
  },
  {
    slug: "man-the-lane",
    term: "Man the Lane",
    aka: ["manning the lane", "man lane", "manned"],
    short: "Being assigned responsibility for overseeing and managing the movement of cards on a specific lane on a Trello board.",
    long: "A production approach used to strictly monitor the movement of tasks. Usually done by the Project Manager or Coordinator, or a Design Ops member.",
    example: "Please man the lane for today to make sure cards are moving accordingly.",
    saidBy: "Don, Team Lead",
    related: ["buffer-lane", "cards", "pipeline", "production-backlogs"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "passed-qa-validation",
    term: "Passed QA Validation",
    aka: ["passed qa", "qa validation", "passed validation"],
    short: "Developed design output that has been thoroughly checked and found to have no remaining bugs or issues after going through DQA.",
    long: "This happens during the DQA process. Once a developed design passes QA validation, it's ready for client handover.",
    example: "Done validating all issues for this page; this has passed QA validation!",
    saidBy: "Lea, Visual Designer",
    related: ["dqa", "validate-issues", "bugs-and-issues"],
    category: "Process Related",
    audience: ["designers", "devs"],
  },
  {
    slug: "pipeline",
    term: "Pipeline",
    aka: ["pipelines"],
    short: "The sequence of steps cards go through to get completed. It gives the team a visual guide on how work moves from start to finish.",
    long: "Important to set up at the start of a project. A pipeline typically has columns for pending, active, approved, and for-review screens; the process can resemble the Trello application.",
    example: "Will be checking the pipeline for the status of our screens.",
    saidBy: "Miro, Project Coordinator",
    related: ["cards", "buffer-lane", "working-file", "working-on-lane"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "production-backlogs",
    term: "Production Backlogs",
    aka: ["production backlog", "backlog", "backlogs"],
    short: "A Trello lane where new tasks from the team or clients are placed before being sorted into their appropriate lanes after assessment.",
    long: "This lane is usually manned by the Project Manager or Coordinator, or a Design Ops member. Cards created by anyone on the production team through Hermes also land here first.",
    example: "I just added a card to our Production Backlog. Please assess and let me know the next steps.",
    saidBy: "Miro, Project Coordinator",
    related: ["ready-for-design", "cards", "man-the-lane"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "raintool",
    term: "Raintool",
    aka: ["rt", "rain tool", "timesheet"],
    short: "Our timekeeping tool, essential for keeping track of tasks and the time spent on them.",
    long: "Always remember to run the appropriate tasks at the correct time, and stop the task if idle. At the end of the day you must also submit your timesheet before logging off.",
    example: "Don't forget to run your Raintool task.",
    saidBy: "Anna, Technical Lead for Development",
    related: ["daily-checkpoint"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "ready-for-design",
    term: "Ready for Design",
    aka: ["rfd", "ready for design lane"],
    short: "Tasks that have been assessed and are now awaiting the design team's attention or action.",
    long: "If a card in the Production Backlog is due soon — usually within 3 days or less — it is placed in the Ready for Design lane in Trello. Look in this column for the most urgent tasks.",
    example: "Moved this to the Ready for Design lane; you may work on this card already!",
    saidBy: "Miles, Design Ops",
    related: ["production-backlogs", "working-on-lane", "cards"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "rework",
    term: "Rework",
    aka: ["reworks", "rework card", "redo"],
    short: "Cards that need to be redone based on client feedback or internal review, often due to changes in scope or specific feedback.",
    long: "A rework card differs from a changelog request in that it involves a very major change, or several revisions on one page that amount to a redesign of it. Can be found in the Trello app or in the Figma file as a tracker.",
    example: "Filed a rework card for this, please work on it.",
    saidBy: "Miles, Design Ops",
    related: ["change-logs", "base-deliverables", "cards"],
    category: "Process Related",
    audience: ["all"],
  },
  {
    slug: "swarm-the-card",
    term: "Swarm the Card",
    aka: ["swarm", "swarming", "swarm card"],
    short: "A production approach where a group of people works only on one card.",
    long: "The team does this to accelerate production of complex work that would take longer if a single resource tackled it alone.",
    example: "Please swarm the card for this deliverable; we need to push for approval by end of day.",
    saidBy: "Miro, Project Coordinator",
    related: ["cards", "man-the-lane"],
    category: "Process Related",
    audience: ["designers"],
  },
  {
    slug: "validate-issues",
    term: "Validate Issues",
    aka: ["validate the issues", "validating issues", "validation"],
    short: "Re-testing and verifying that previously identified bugs or issues have been resolved, ensuring the problem has been adequately addressed.",
    long: "Usually used in the context of DQA, after a dev addresses a bug filed by the design team. This is the next step before the issue can be marked as resolved.",
    example: "Can you please validate the issues on this card?",
    saidBy: "Marie, Frontend Developer",
    related: ["dqa", "bugs-and-issues", "passed-qa-validation"],
    category: "Process Related",
    audience: ["designers", "devs"],
  },
  {
    slug: "working-on-lane",
    term: "Working on Lane",
    aka: ["working on", "working lane", "working on design lane"],
    short: "Where cards are placed when at least one designer is actively working on a card.",
    long: "This shows what cards are active. If a card is on hold, the team may add a tag to indicate its status.",
    example: "I've moved the card I'm working on to the Working on Lane already.",
    saidBy: "Monique, Content Writer",
    related: ["buffer-lane", "ready-for-design", "cards", "wip"],
    category: "Process Related",
    audience: ["all"],
  },

  /* ---------------------------------------------------------------
     DESIGN PROCESS
     --------------------------------------------------------------- */
  {
    slug: "asset-generation",
    term: "Asset Generation",
    aka: ["asset gen", "generate assets", "mj", "midjourney"],
    short: "The process in which the team produces images through Midjourney (an AI program) using text prompts.",
    long: "AI-generated assets were integrated into our workflow to address the volume of assets the team needs to produce. Typically practiced on internal projects and on projects where we have a go signal from the client.",
    example: "Proceed with asset generation with MJ for this set of cards.",
    saidBy: "Gwyn, Assets Team",
    related: ["level-matching", "icons", "key-visual"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "bake-spacing",
    term: "Bake Spacing",
    aka: ["bake", "baking spacing", "bake vertical spacers"],
    short: "A function in the Frost Design Utilities plugin that automatically generates spacers based on a designer's rough composition of elements.",
    long: "Meant to help the designer concentrate on designing the look of the screens. Using bake spacing keeps us consistent without worrying whether the spacing is correct.",
    example: "Use bake spacing on this later during refinement.",
    saidBy: "Val, Team Lead",
    related: ["spacers", "auto-layout", "paddings", "margins"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "componentization",
    term: "Componentization",
    aka: ["componentize", "componentise", "componentizing"],
    short: "The process in which the team extracts elements and sections in our screens and turns them into components.",
    long: "After high-fidelity screens are approved, the team componentizes elements that aren't components yet. The screens are then released to the client after componentization.",
    example: "Componentize these screens before adding them back into the flow structure.",
    saidBy: "Dar, Visual Designer",
    related: ["components", "atomizer", "base-component", "production-grade-components"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "design-cascade",
    term: "Design Cascade",
    aka: ["cascade", "cascading", "cascade this"],
    short: "The process of applying or laying out components, elements, or even sections to a certain screen.",
    long: "We arrange design elements such as text, images, or buttons in a well-organized and structured manner. This step happens when the team needs to apply reusable elements or components to a screen design or layout.",
    example: "Cascade this design into the other screen sizes.",
    saidBy: "Dar, Visual Designer",
    related: ["components", "templates", "high-fidelity-designs"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "design-review",
    term: "Design Review",
    aka: ["dr", "design reviews"],
    short: "The last step in the design process, where a Lead Designer evaluates output and gives appropriate revisions if needed before it is approved.",
    long: "Usually the step right before we submit the design for client approval or pass. Lead Designers must check every detail before approving, to reduce errors and the risk of client revisions.",
    example: "Will be moving this for design review.",
    saidBy: "Wilmer, Visual Designer",
    related: ["peer-review", "first-pass", "high-fidelity-designs"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "first-pass",
    term: "First Pass",
    aka: ["fp", "first-pass", "first passes"],
    short: "The informal evaluation of output, usually done to check if it's on the right track. Done right before moving output to Peer Review or Design Review.",
    long: "This step happens before we move the tracker or task for formal review. It matters because it lets us quickly explore ideas, gather feedback, and iterate on the design.",
    example: "Can I do a first pass for this? Need to check if it's the right decision.",
    saidBy: "Mariel, Graphic Designer",
    related: ["peer-review", "design-review"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "flattened",
    term: "Flattened",
    aka: ["flatten", "flattening", "detach", "detached"],
    short: "Detached screens or components. You can use the flatten function in the Frost Design Utilities plugin to flatten multiple components in one click.",
    long: "Usually done right before client hand-off. Flattening ensures component-level changes won't affect the screens, and that the release file retains the original designs submitted.",
    example: "These screens have been flattened and are ready for client handover.",
    saidBy: "Clarence, Visual Designer",
    related: ["components", "high-fidelity-designs", "working-file"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "level-matching",
    term: "Level-Matching",
    aka: ["level match", "level matching", "levels"],
    short: "Tweaking the colors and light of an image so it matches other assets present in the output.",
    long: "Usually done after cropping or generating an asset. We use Photoshop in Adobe Creative Cloud when we have to level-match an asset.",
    example: "Done level-matching these photos, will send them for design review next.",
    saidBy: "Mariel, Graphic Designer",
    related: ["asset-generation", "design-review"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "normalization",
    term: "Normalization",
    aka: ["normalize", "normalise", "normalizing"],
    short: "The process of ensuring consistency across all components and screens.",
    long: "It ensures design elements such as colors, typography, spacing, and components are consistent across all screens. It helps designers create a coordinated user experience and establish design principles.",
    example: "Normalize these set of buttons and its variants.",
    saidBy: "Don, Team Lead",
    related: ["thanos", "design-system", "sticker-sheet", "typescale"],
    category: "Design Process",
    audience: ["designers"],
  },
  {
    slug: "peer-review",
    term: "Peer Review",
    aka: ["pr", "peer reviews", "peer-review"],
    short: "A step in the design process where a fellow designer evaluates your output and gives comments. Done before moving output either for Design Review or Approved.",
    long: "Typically done by junior or mid-level resources before passing it for review to their senior or team lead. This ensures you're following Frost standards by having another set of eyes check your output.",
    example: "Can you peer review this before I pass it for design review?",
    saidBy: "Wilmer, Visual Designer",
    related: ["design-review", "first-pass"],
    category: "Design Process",
    audience: ["all"],
  },
  {
    slug: "prototype",
    term: "Prototype",
    aka: ["prototypes", "proto", "prototyping"],
    short: "A simulation of the interactions within a set of high-fidelity screens, done to test and validate ideas before development.",
    long: "This is done for the benefit of the devs or our clients. Your prototype must show the flow end-to-end, including negative scenarios if possible. You can create it in Figma.",
    example: "I created a prototype to show the interaction for these set of screens.",
    saidBy: "Clarence, Visual Designer",
    related: ["high-fidelity-designs", "happy-path", "error-scenario", "related-scenario"],
    category: "Design Process",
    audience: ["designers", "devs"],
  },
  {
    slug: "thanos",
    term: "Thanos",
    aka: ["thanos plugin", "run thanos"],
    short: "A plugin developed by Frost to automate the normalization process.",
    long: "Using Thanos is important at Frost as it normalizes spacings, colors, and even text styles. Where there are numerous screen designs, the design team collates them and runs the Thanos plugin.",
    example: "We'll run Thanos to normalize the typesetting.",
    saidBy: "Dar, Visual Designer",
    related: ["normalization", "typescale", "atomizer"],
    category: "Design Process",
    audience: ["designers"],
  },

  /* ---------------------------------------------------------------
     DESIGN TERMS
     --------------------------------------------------------------- */
  {
    slug: "atomizer",
    term: "Atomizer",
    aka: ["atomize", "atomise", "atomizing"],
    short: "A function in the Frost Design Utilities plugin that automates creating components by breaking a big section down into smaller components.",
    long: "Used in the screen design process to create rough components automatically. It's still important to thoroughly check the roughly componentized elements to avoid errors.",
    example: "Atomize that section component.",
    saidBy: "Bea, Visual Designer",
    related: ["componentization", "local-components", "low-level-components"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "auto-layout",
    term: "Auto Layout",
    aka: ["autolayout", "auto-layout", "al"],
    short: "A feature in Figma that lets designers build layouts that adapt based on the settings applied. A requirement for high-fidelity screens.",
    long: "Applying auto-layout is part of Frost standards, meaning it should be done for all high-fidelity work that is submitted. This ensures screens are built efficiently and can be adjusted easily.",
    example: "Don't forget to auto-layout all your elements before passing it for design review.",
    saidBy: "Don, Team Lead",
    related: ["spacers", "bake-spacing", "paddings", "visual-alignment"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "equally-spaced",
    term: "Equally Spaced",
    aka: ["equal spacing", "equally-spaced", "even spacing"],
    short: "An element having equal spacing, or appearing to have equal spacing (visual alignment), on all sides.",
    long: "Checking whether elements have the same spacing on all sides is the default way of checking alignment. We often use grids or rectangle shapes to check whether the design is visually aligned.",
    example: "Make sure the elements are equally spaced for the form component.",
    saidBy: "Bea, Visual Designer",
    related: ["visual-alignment", "vertically-aligned", "margins", "paddings"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "error-scenario",
    term: "Error Scenario",
    aka: ["error scenarios", "error path", "negative scenario"],
    short: "A path in a flow structure detailing all possible errors the user may experience — API failure, incorrect input, and so on.",
    long: "The error path is crucial so the design team knows what needs to be addressed and how to guide users through these issues. After establishing the happy path, error scenarios also go into the screen design flow in our Figma file.",
    example: "Don't forget to provide error scenarios for this flow.",
    saidBy: "Val, Visual Designer",
    related: ["happy-path", "related-scenario", "prototype"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "happy-path",
    term: "Happy Path",
    aka: ["happy paths", "ideal path", "happy flow"],
    short: "The most ideal user flow in a flow structure. There should be a clear path from entry to the end state.",
    long: "It represents the ideal user journey. After creating a happy path, there should also be error handling and alternative paths, to achieve a simple, efficient, robust and inclusive user experience.",
    example: "Ensure that the happy path has all complete steps in the flow structure.",
    saidBy: "Don, Team Lead",
    related: ["error-scenario", "related-scenario", "prototype"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "leading-element",
    term: "Leading Element",
    aka: ["leading icon", "leading elements"],
    short: "The first element in a sequence of elements.",
    long: "It serves as a focal point guiding users' attention and actions. You can do this using a spot illustration or icon before some text.",
    example: "Can you enable the leading icon on this title component?",
    saidBy: "Val, Team Lead",
    related: ["trailing-element", "icons", "components"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "margins",
    term: "Margins",
    aka: ["margin"],
    short: "The space around an element.",
    long: "It helps establish visual balance and composition within a design by giving the content space to breathe. Along with paddings, we use this to provide a clear and tidy boundary within our design.",
    example: "Make sure the elements are aligned to the margin.",
    saidBy: "Miles, Visual Designer",
    related: ["paddings", "spacers", "equally-spaced"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "modular-scale",
    term: "Modular Scale",
    aka: ["modular scales", "scale ratio"],
    short: "A sequence of numbers that increase or decrease based on a certain ratio. Used in the 8pt grid and the typescale.",
    long: "Since this is typically applied in typesetting, it's used at the beginning of a project. Make sure this principle is applied to conform to Frost standards.",
    example: "Apply the modular scale when working on the typesetting for this.",
    saidBy: "Val, Team Lead",
    related: ["typescale", "spacers", "normalization"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "orphan",
    term: "Orphan",
    aka: ["orphans", "orphaned word"],
    short: "A single word that sits at the bottom of a paragraph of text.",
    long: "Preventing orphans improves readability, aesthetics, and the overall user experience of screen designs. As much as possible we check paragraphs for orphans and eliminate them, to follow Frost's design standards.",
    example: "Please address this orphan on this paragraph of text.",
    saidBy: "Don, Team Lead",
    related: ["copy", "typescale"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "paddings",
    term: "Paddings",
    aka: ["padding"],
    short: "The space between an element's border and its content.",
    long: "Implementing padding correctly is crucial for creating visually pleasing, user-friendly, well-structured interfaces. Paddings can be applied not just around content, but also around icons.",
    example: "Can you increase the padding on this element?",
    saidBy: "Bea, Visual Designer",
    related: ["margins", "spacers", "auto-layout", "equally-spaced"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "related-scenario",
    term: "Related Scenario",
    aka: ["related scenarios", "parallel flow"],
    short: "Other scenarios that don't follow the ideal customer journey but are still relevant to the flow.",
    long: "It helps ensure the interface can handle different user situations effectively. This is different from our error or happy path, as it's closely connected to the main user journey but sits in a parallel flow.",
    example: "Make sure you cover related scenario as well.",
    saidBy: "Val, Visual Designer",
    related: ["happy-path", "error-scenario", "prototype"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "rescale",
    term: "Rescale",
    aka: ["rescaling", "scale k", "resize icon"],
    short: "Resizing an icon, usually using the Scale (K) function in Figma.",
    long: "You may rescale an icon if you need a different size but don't have time to request a new one. Just make sure to double check that the elements look alright in the rescaled icon.",
    example: "Rescale this icon from 52px to 64px.",
    saidBy: "Lea, Visual Designer",
    related: ["icons", "reskin"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "reskin",
    term: "Reskin",
    aka: ["reskinning", "re-skin", "reskins"],
    short: "A redesign of a screen or set of screens that follows the blockscreens from the client very closely.",
    long: "Done when a client specifically requests that the design on our end retain the same structure as the screens from their end. It's still possible to make a recommendation if necessary.",
    example: "The scope of this deliverable is just a reskin of the blockscreens from the client.",
    saidBy: "Don, Team Lead",
    related: ["block-screen", "high-fidelity-designs", "rework"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "trailing-element",
    term: "Trailing Element",
    aka: ["trailing icon", "trailing elements"],
    short: "The last element in a sequence of elements.",
    long: "It gives supplementary information as well as additional value in our screen designs. You can use a spot illustration or icon for this.",
    example: "Can you add a trailing icon to this title component?",
    saidBy: "Bea, Visual Designer",
    related: ["leading-element", "icons", "components"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "typescale",
    term: "Typescale",
    aka: ["type scale", "typesetting", "type styles"],
    short: "The progression of font styles, usually also segregated by hierarchy and/or screen size.",
    long: "It's a set of different text sizes and styles used in our design. We use this to ensure the text in our user interface design looks good and is easy to read.",
    example: "Please set the typescale for this project.",
    saidBy: "Val, Visual Designer",
    related: ["modular-scale", "normalization", "design-system", "thanos"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "vertically-aligned",
    term: "Vertically Aligned",
    aka: ["vertical alignment", "vertically align"],
    short: "The alignment of elements from a top to bottom direction.",
    long: "It provides visual structure in our designs, making them logical and consistent. This applies not only to assets or icons but to the content applied within the design as well.",
    example: "Can you vertically align these elements?",
    saidBy: "Gwyn, Visual Designer",
    related: ["visual-alignment", "equally-spaced", "auto-layout"],
    category: "Design Terms",
    audience: ["designers"],
  },
  {
    slug: "visual-alignment",
    term: "Visual Alignment",
    aka: ["visually aligned", "optical alignment"],
    short: "An element that appears to be balanced against other surrounding elements.",
    long: "Something we constantly have to be aware of when we design. Sometimes aligning elements automatically through auto-layout isn't enough — you may use the visual alignment function in our Design Utilities plugin.",
    example: "Make sure the icon is visually aligned to the content.",
    saidBy: "Gwyn, Visual Designer",
    related: ["vertically-aligned", "equally-spaced", "auto-layout"],
    category: "Design Terms",
    audience: ["designers"],
  },

  /* ---------------------------------------------------------------
     DESIGN ARTIFACTS
     --------------------------------------------------------------- */
  {
    slug: "base-component",
    term: "Base Component",
    aka: ["base components", ".base", "master component"],
    short: "The master component other variants are created from. Changes made at the base component level cascade quickly to other variants.",
    long: "It serves as a foundational element for creating consistent, reusable UI elements. These can be found in the inner layers of the component and are labelled with a \".base/\".",
    example: "Apply these to the base component so its variants will update as well.",
    saidBy: "Clarence, Visual Designer",
    related: ["components", "production-grade-components", "componentization", "sticker-sheet"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "block-screen",
    term: "Block Screen",
    aka: ["block screens", "blockscreen", "blockscreens"],
    short: "Initial screens provided by the client, used as references for redesign or cleanup before finalizing into high-fidelity screens.",
    long: "It's important to study the block screen before proceeding with the redesign, since it has the content to include in the new set of screens. Block screen can also refer to low- to mid-fidelity screens the team creates from scratch.",
    example: "We just received the block screens from the client; we'll assess them before proceeding with screen design.",
    saidBy: "Val, Team Lead",
    related: ["reskin", "low-fidelity-designs", "high-fidelity-designs"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "components",
    term: "Components",
    aka: ["component", "comps"],
    short: "A reusable element used across multiple screens and flows, ensuring consistency throughout the screen designs.",
    long: "The team can create rough components while designing, or finalize the components of all elements after the screens are approved. Components are transferred to the Sticker Sheet library if approved.",
    example: "Please apply our existing components to these screens during production.",
    saidBy: "Wilmer, Visual Designer",
    related: ["base-component", "local-components", "high-level-components", "low-level-components", "sticker-sheet"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "copy",
    term: "Copy",
    aka: ["microcopy", "content", "copywriting"],
    short: "The textual content provided by the Content team to be used in the screen designs.",
    long: "Copy can be added directly to screens in the Design team's working file, or written in Google Docs. Both teams need to ensure the quality of every applied copy.",
    example: "Make sure that the screens has the updated copy from the Content team.",
    saidBy: "Val, Visual Designer",
    related: ["orphan", "working-file", "high-fidelity-designs"],
    category: "Design Artifacts",
    audience: ["designers", "content"],
  },
  {
    slug: "design-system",
    term: "Design System",
    aka: ["ds", "design systems"],
    short: "A centralized library containing a collection of elements, components, colors, typography, and other standards used to ensure consistency and efficiency in product design.",
    long: "Building a design system is a long, complicated process usually done after seeing patterns from several high-fidelity screens. It's then expanded through the entire project lifecycle.",
    example: "Maintain the design system and ensure it is always up to date.",
    saidBy: "JP, Chief Creative Officer",
    related: ["sticker-sheet", "components", "typescale", "normalization"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "dev-components",
    term: "Dev Components",
    aka: ["dev component", "developer components"],
    short: "Reference elements used by developers during the development phase. These often display the spacers and screens provided by the client.",
    long: "Used as references for redesign or cleanup before finalizing into high-fidelity screens. It's important that these are well-documented and communicated clearly to developers, so they can build the user interface as intended.",
    example: "Please set up the dev components for the dev team.",
    saidBy: "Clarence, Visual Designer",
    related: ["components", "spacers", "high-fidelity-designs", "dqa"],
    category: "Design Artifacts",
    audience: ["designers", "devs"],
  },
  {
    slug: "high-fidelity-designs",
    term: "High-Fidelity Designs",
    aka: ["hifi", "hi-fi", "high fidelity", "high-fi", "hi fi screens"],
    short: "The final production-ready screens produced by the design team, ready for hand-off to clients and/or development.",
    long: "These are the polished, final version of our design work. Usually provided to clients as a detailed roadmap for turning our design concepts into a fully functional design product.",
    example: "These high-fidelity designs are good to go. Send these for client approval.",
    saidBy: "JP, Chief Creative Officer",
    related: ["low-fidelity-designs", "block-screen", "design-review", "flattened"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "high-level-components",
    term: "High-Level Components",
    aka: ["high level component", "hlc", "high-level"],
    short: "More complex components composed of smaller, low-level components.",
    long: "These are like major sections in our design, finalized in the Figma file or even in the Sticker Sheet. High-Level Components provide structure for our screen designs, making them organized and functional.",
    example: "This card group component is a high-level component.",
    saidBy: "Dar, Visual Designer",
    related: ["low-level-components", "components", "base-component"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "icons",
    term: "Icons",
    aka: ["icon", "iconography"],
    short: "Vector design elements acting as a visual representation for an item, communicating the idea.",
    long: "Icons help users understand quickly without the need for lengthy text explanations or labels in screen design. The Design team must ensure the icons created are clear and consistent to guarantee a good user experience.",
    example: "This icon is now ready for client approval, thanks.",
    saidBy: "Lea, Visual Designer",
    related: ["rescale", "leading-element", "trailing-element", "key-visual"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "key-visual",
    term: "Key Visual",
    aka: ["kv", "key visuals"],
    short: "A graphic element conveying a particular feel or idea that designers can use as a reference for other related deliverables.",
    long: "Considered important since it's a visual item that conveys specific direction. Receiving a Key Visual from our client can be helpful to our designs.",
    example: "Please check the KV from the client for the direction to follow with this deliverable.",
    saidBy: "Miles, Design Ops",
    related: ["asset-generation", "icons", "templates"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "local-components",
    term: "Local Components",
    aka: ["local component", "rough components", "rough component"],
    short: "Components created and used on a single file only, usually the main working file.",
    long: "Usually done in the working file along with the screen designs; can be called a rough component. Although they may be rough, we need to ensure proper naming and structure are still applied.",
    example: "We need to migrate our local components into our sticker sheet file.",
    saidBy: "Bea, Visual Designer",
    related: ["components", "sticker-sheet", "atomizer", "working-file"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "low-fidelity-designs",
    term: "Low-Fidelity Designs",
    aka: ["lofi", "lo-fi", "low fidelity", "wireframes", "wireframe"],
    short: "Wireframes or sketches done quickly, usually to test the functionality and flow of a product.",
    long: "This step constructs a rough sketch — basically a blueprint of the screen design. Doing this is quicker for gathering feedback and developing the final screen designs.",
    example: "Proceed with low-fidelity first to flesh out the structure of your page.",
    saidBy: "Don, Team Lead",
    related: ["high-fidelity-designs", "block-screen", "prototype"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "low-level-components",
    term: "Low-Level Components",
    aka: ["low level component", "llc", "low-level"],
    short: "Less complex or smaller components that can be combined with other components to form a high-level component.",
    long: "These are produced typically in the beginning stages of a project. They can then be further refined later down the line into high-level components.",
    example: "This button component is a low-level component.",
    saidBy: "Dar, Visual Designer",
    related: ["high-level-components", "components", "atomizer"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "production-grade-components",
    term: "Production Grade Components",
    aka: ["production-grade", "production grade component", "prod grade"],
    short: "The final form of components, properly constructed and ready for development or hand-off to a client.",
    long: "Elements that make up a production-grade component are properly named layers, a base component, proper spacing, and text styles. This is to ensure it's ready for development.",
    example: "Make sure these components are production-grade before handing them over to the devs.",
    saidBy: "Don, Team Lead",
    related: ["base-component", "components", "surfboard", "componentization"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "screen-context",
    term: "Screen Context",
    aka: ["context", "in context"],
    short: "The big-picture view of an element alongside other surrounding elements, sections, and content.",
    long: "Usually done to test whether your icon or asset works with the actual screen it will be placed in. This may be done during the WIP phase or after your output has been approved by the client.",
    example: "Apply these assets to its screen context to check if it works.",
    saidBy: "Rey, Graphic Designer",
    related: ["icons", "screen-index", "wip"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "screen-index",
    term: "Screen Index",
    aka: ["indexing", "indexed", "index screens"],
    short: "The process of gathering and laying out related screens horizontally. Usually done in preparation for screen design or normalization.",
    long: "Typically done to see the similarities or differences of screens in a certain flow. Make sure screens that are already indexed are set to low opacity, to track which ones are left.",
    example: "Do a screen index of all the screens in the flow structure to prepare for screen design.",
    saidBy: "Val, Team Lead",
    related: ["normalization", "screen-context", "working-file"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "spacers",
    term: "Spacers",
    aka: ["spacer", "spacing component"],
    short: "Spacing components that follow the 8pt grid, found in the Frost Design Utilities plugin. They help us design using auto-layout more efficiently.",
    long: "Used whenever you want to auto-layout several elements together, since they reduce the number of layers for items with auto-layout. These are only used in between elements, not for padding surrounding the content.",
    example: "Don't forget to use our spacers between elements with auto-layout.",
    saidBy: "Val, Visual Designer",
    related: ["auto-layout", "bake-spacing", "paddings", "modular-scale"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "sticker-sheet",
    term: "Sticker Sheet",
    aka: ["sticker sheets", "stickersheet", "ss"],
    short: "The format in which we display our components. It lets designers easily identify and grab components from our Design System or Component Library in an organized manner.",
    long: "If new components are introduced to the Figma file, the design team must maintain the sticker sheet regularly. This is essential as it ensures consistency across the high-fidelity screen designs.",
    example: "Migrate these components to our Sticker Sheet and make sure to follow the guidelines.",
    saidBy: "Bea, Visual Designer",
    related: ["design-system", "components", "local-components", "base-component"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "templates",
    term: "Templates",
    aka: ["template"],
    short: "A pre-existing design that can be reused as the basis for creating new designs. It serves as a reference for the look and structure of screens or components.",
    long: "These are created once a certain structure that can be repeated on other pages is established. This can also apply to smaller elements like sections or components.",
    example: "Refer to our existing templates for the layout to follow in these screens.",
    saidBy: "Don, Team Lead",
    related: ["design-cascade", "components", "high-level-components"],
    category: "Design Artifacts",
    audience: ["designers"],
  },
  {
    slug: "wip",
    term: "WIP",
    aka: ["work in progress", "w.i.p", "wips"],
    short: "Shorthand for \"Work in Progress\".",
    long: "Typically seen as a label on our Figma pages, for example: [WIP] High-Fidelity Screens. You may also use it to describe ongoing work when you give your progress updates.",
    example: "This dashboard screen design is currently a WIP.",
    saidBy: "Lea, Visual Designer",
    related: ["working-file", "working-on-lane", "screen-context"],
    category: "Design Artifacts",
    audience: ["all"],
  },
  {
    slug: "working-file",
    term: "Working File",
    aka: ["working files", "main file"],
    short: "The active Figma file where the design team works on their output.",
    long: "Important to properly set up at the beginning of a project. Some key pages to have are: Working Area (with a pipeline), Individual Workspaces, Archive, Spacers, Resources, and Cover page.",
    example: "Make sure the working file is set up and ready for production.",
    saidBy: "Val, Visual Designer",
    related: ["pipeline", "local-components", "wip", "screen-index"],
    category: "Design Artifacts",
    audience: ["designers"],
  },

  /* ---------------------------------------------------------------
     MISCELLANEOUS
     --------------------------------------------------------------- */
  {
    slug: "breakfast-talk",
    term: "Breakfast Talk",
    aka: ["breakfast talks", "bt", "chika"],
    short: "A gathering of the Design Team during downtime where we \"chika\" or talk about non-work related topics.",
    long: "Done as a bonding activity for the team. Activities can range from random chika, games, and so on.",
    example: "Let's have a Breakfast Talk later at 11AM!",
    saidBy: "Don, Team Lead",
    related: ["daily-checkpoint", "ho"],
    category: "Miscellaneous",
    audience: ["designers"],
  },
  {
    slug: "gate-one",
    term: "Gate One",
    aka: ["gate 1", "g1", "gate-one"],
    short: "The training period a new designer goes through before joining the production team.",
    long: "During this period, the new member goes through a series of design drills repeatedly until they can perfect them. This ensures they can keep up with the production process alongside the rest of the team.",
    example: "Balik ka nga sa Gate One.",
    saidBy: "Clarence, Visual Designer",
    related: ["peer-review", "surfboard"],
    category: "Miscellaneous",
    audience: ["designers"],
  },
  {
    slug: "ho",
    term: "HO",
    aka: ["hangout", "hangouts", "google hangouts", "h.o", "hos"],
    short: "Shorthand for Google Hangouts, often used when needing to align with someone on the team.",
    long: "You may call for a HO meeting whenever you need to quickly align over a task, recalibrate with your team, or have a coaching session. You can also schedule HO meetings through Google Calendar.",
    example: "@Sab HO so we can align on the next steps of this project. Here's the link.",
    saidBy: "JP, Chief Creative Officer",
    related: ["daily-checkpoint", "daily-standup", "breakfast-talk"],
    category: "Miscellaneous",
    audience: ["all"],
  },
  {
    slug: "jhemerlyn",
    term: "Jhemerlyn",
    aka: ["jhem", "jhemerlin"],
    short: "The face of stock photos, specifically for smiling Asian. You've probably seen her already.",
    long: "A Design-team inside joke.",
    example: "Yan na naman si Jhemerlyn, nasa ad ng [redacted].",
    saidBy: "Miles, Visual Designer",
    related: ["asset-generation", "surfboard"],
    category: "Miscellaneous",
    audience: ["designers"],
  },
  {
    slug: "surfboard",
    term: "Surfboard",
    aka: ["surfboards", "surfboard is waving"],
    short: "Associated with Don, a mid-level designer on the team, as a warning to properly name your layers on Figma — something we're strict about at Frost.",
    long: "A Design-team inside joke about layers. Make sure to use the proper naming conventions; examples are: #blurb, #header, #label, content-container, Tag Component.",
    example: "Name your layers, mapapalo ka ng surfboard nyan.",
    saidBy: "Don, Visual Designer",
    related: ["production-grade-components", "components", "gate-one"],
    category: "Miscellaneous",
    audience: ["designers"],
  },
];

export default VOCABULARY;
